version: "2"
services:
  web:
    build: .
    ports:
      - "5555:5555"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"